---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: python-app-frontend
spec:
  selector:
    matchLabels:
      app: python-app-frontend
  replicas: 3 # tells deployment to run 1 pods matching the template
  template: 
    metadata:
      labels:
        app: python-app-frontend
    spec:
      containers:
      - name: python-app-frontend
        image: 481195286011.dkr.ecr.us-east-1.amazonaws.com/sample-python-frontend:dev
        ports:
        - containerPort: 5000
---

apiVersion: v1
kind: Service
metadata:
  name: python-app-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: python-app-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
